package com.ers.test;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.ers.dao.EmployeeDao;
import com.ers.dao.EmployeeDaoImpl;
import com.ers.model.Employee;

public class EmployeeDAOTest {
	
	@Before
	public void setUp() throws Exception {
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void testAddNewEmployee() {
		EmployeeDao edao = EmployeeDaoImpl.getInstance();
		Employee e1 = new Employee(100,"Testfname","Testlname","Test@gmail.com","01-01-1990","111-111-1111","123 Test St","Testcity","Teststate","Testcountry","Testzip",true);
		// int id, String firstname,String lastname,String email,String birthdate,String phoneNum,String address,String city,String state, String country, String zip, Boolean isManager
		boolean success = edao.addNewEmployee(e1);
		if (success) {
			Employee rtnEmp = edao.getEmployeeById(100);
			// CANNOT USE GETEMPLOYEEBYID BECAUSE EMPLOYEE ID IS GENERATED BY A SEQUENCE IN THE DB
			assertEquals(rtnEmp.getFirstname(), e1.getFirstname());			
		}
		else
			fail("The new employee failed to add to the database");
	}
}
